# POST http://localhost:3001/api/v1/auth/login
# Content-Type: application/json

# {
#   "username": "Administrador",
#   "password": "11102004"
# }

POST http://localhost:3001/api/v1/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc0NjE1ODAzN30.vEM05y-IvJ-W9qKXRN3LBwKB3gw3sLcsfDdJsu0gDuA

{
    "username": "Reynaldo",
    "role": "admin",
    "pictureUrl": "",
    "password": "jIz5e$4$49$&4LR"
  }